name: Nanaco ANA Monitor

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日UTC 0時（日本時間9時）に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitor script
        env:
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}
        run: python monitor.py

      - name: Commit state changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add state.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update state [$(date)]"
            git push
          fi
